process_attributes={"DY":
                    {
                        "fileN":["DY.root"],
                        "xs":6077.22,
                        "color":632 ,
                        "instack":False,
                        "leg":"DY",
                        "order":0,
                    },
                    "WJet":
                    {
                        "fileN":["WJets.root"],
                        "xs":61526.7,
                        "color":593,
                        "instack":False,
                        "leg":"W+jets",
                        "order":2,
                    },
                    "osWW":
                    {
                        "fileN":["osWW.root"],
                        "xs":11.09,
                        "color":425,
                        "instack":True,
                        "leg":"VV",
                        "order":3,
                    },
                    "ssWW":
                    {
                        "fileN":["ssWW.root"],
                        "xs":0.04932,
                        "color":425,
                        "instack":False,
                        "leg":"VV",
                        "order":3,
                    },
                    "WZ_ew":
                    {
                        "fileN":["WZ_ew.root"],
                        "xs":0.0163,
                        "color":425,
                        "instack":False,
                        "leg":"VV",
                        "order":3,
                    },
                    "WZ_qcd":
                    {
                        "fileN":["WZ_qcd.root"],
                        "xs":5.213,
                        "color":425,
                        "instack":False,
                        "leg":"VV",
                        "order":3,
                    },
                    "ZZ":
                    {
                        "fileN":["ZZ.root"],
                        "xs":0.0086,
                        "color":425,
                        "instack":False,
                        "leg":"VV",
                        "order":3,
                    },
                    "ZG_ew":
                    {
                        "fileN":["ZG_ew.root"],
                        "xs":0.1097,
                        "color":425,
                        "instack":False,
                        "leg":"VV",
                        "order":3,
                    },
                    "WWW":
                    {
                        "fileN":["WWW.root"],
                        "xs":0.2086,
                        "color":811,
                        "instack":True,
                        "leg":"VVV",
                        "order":4,
                    },
                    "WWZ":
                    {
                        "fileN":["WWZ.root"],
                        "xs":0.1707,
                        "color":811,
                        "instack":True,
                        "leg":"VVV",
                        "order":4,
                    },
                    "WZZ":
                    {
                        "fileN":["WZZ.root"],
                        "xs":0.05709,
                        "color":811,
                        "instack":False,
                        "leg":"VVV",
                        "order":4,
                    },
                    "ZZZ":
                    {
                        "fileN":["ZZZ.root"],
                        "xs":0.01476,
                        "color":811,
                        "instack":False,
                        "leg":"VV",
                        "order":4,
                    },
                    "TTTo2L":
                    {
                        "fileN":["TTTo2L.root","TTTo2L_1.root"],
                        "xs":88.3419,
                        "color":600,
                        "instack":False,
                        "leg":"tt",
                        "order":1,
                    },

                    "TTTo1L":
                    {
                        "fileN":["TTTo1L.root"],
                        "xs":365.4574,
                        "color":600,
                        "instack":False,
                        "leg":"tt",
                        "order":1,
                    },
                    
                    "ttH":
                    {
                        "fileN":["ttH.root"],
                        "xs":0.5269,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttWtoLNu":
                    {
                        "fileN":["ttWtoLNu.root"],
                        "xs":0.1792,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttWtoQQ":
                    {
                        "fileN":["ttWtoQQ.root"],
                        "xs":0.3708,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttZ":
                    {
                        "fileN":["ttZ.root"],
                        "xs":0.2589,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttZtoQQ":
                    {
                        "fileN":["ttZtoQQ.root"],
                        "xs":0.6012,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttWW":
                    {
                        "fileN":["ttWW.root"],
                        "xs":0.007003,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttWZ":
                    {
                        "fileN":["ttWZ.root"],
                        "xs":0.002453,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "ttZZ":
                    {
                        "fileN":["ttZZ.root"],
                        "xs":0.001386,
                        "color":876,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },

                    "tzq":
                    {
                        "fileN":["tzq.root"],
                        "xs":0.07561,
                        "color":396,
                        "instack":False,
                        "leg":"tzq",
                        "order":7,
                    },

                    "tW":
                    {
                        "fileN":["tW.root"],
                        "xs":35.85,
                        "color":920,
                        "instack":False,
                        "leg":"single t",
                        "order":5,
                    },
                    "tbarW":
                    {
                        "fileN":["tbarW.root"],
                        "xs":35.85,
                        "color":920,
                        "instack":False,
                        "leg":"single t",
                        "order":5,
                    },
                    "tsch":
                    {
                        "fileN":["tsch.root"],
                        "xs":3.36,
                        "color":920,
                        "instack":False,
                        "leg":"single t",
                        "order":5,
                    },
                    "t_tch":
                    {
                        "fileN":["t_tch.root"],
                        "xs":136.02,
                        "color":920,
                        "instack":False,
                        "leg":"single t",
                        "order":5,
                    },
                    "tbar_tch":
                    {
                        "fileN":["tbar_tch.root"],
                        "xs":80.95,
                        "color":920,
                        "instack":False,
                        "leg":"single t",
                        "order":5,
                    },
                    "ttWH":
                    {
                        "fileN":["ttWH.root"],
                        "xs":0.00114,
                        "color":796,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },
                    "ttZH":
                    {
                        "fileN":["ttZH.root"],
                        "xs":0.00113,
                        "color":796,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },
                    "tttJ":
                    {
                        "fileN":["tttJ.root"],
                        "xs":0.0004,
                        "color":796,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },
                    "tttW":
                    {
                        "fileN":["tttW.root"],
                        "xs":0.00073,
                        "color":796,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    },
                    "tttt":
                    {
                        "fileN":["tttt.root"],
                        "xs":0.0082,
                        "color":796,
                        "instack":False,
                        "leg":"tt+X/XX",
                        "order":6,
                    }
                    }


import yaml
f = open('process_attributes.yaml', 'w+')
yaml.dump(process_attributes, f, allow_unicode=True, default_flow_style=False)
